[package]
name = "image-filters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wgpu = "0.12"
bytemuck = { version = "1.7", features = ["derive"] }
pollster = "0.2"
